### ISSUE TITLE
`overrideComments` option doesn't work

### ISSUE THREAD

**Issue by noah-nuebling** [FlineDev/BartyCrouch#261]
Hi! The `overrideComments` option doesn't seem to work for me.

I can only get the comments to change in my `Localizable.strings` file if I first manually delete the comment from the `.strings` file before running `bartycrouch update`.

I've tested this on macOS 13.0 Beta 5 through Beta 8, using bartycrouch 4.11.0, and my `.bartycrouch.toml` looks like this:

```toml
[update]
tasks = ["interfaces", "code", "normalize"]

[update.interfaces]
paths = ["app", "helper", "accomplice"]
subpathsToIgnore = [".git", "carthage", "pods", "build", ".build", "docs", "frameworks", "tests", "*/external", "*/SupportFiles", "*/iOS-Polynomial-Regression-master"]
defaultToBase = false
ignoreEmptyStrings = false
unstripped = false
ignoreKeys = ["#bartycrouch-ignore!", "#bc-ignore!", "#i!"]

[update.code]
overrideComments = true
codePaths = ["app", "helper", "accomplice"]
subpathsToIgnore = [".git", "carthage", "pods", "build", ".build", "docs", "frameworks", "tests", "*/external", "*/SupportFiles", "*/iOS-Polynomial-Regression-master"]
localizablePaths = ["./Localization"]
defaultToKeys = false
additive = false
unstripped = false
plistArguments = true
ignoreKeys = ["#bartycrouch-ignore!", "#bc-ignore!", "#i!"]

[update.transform]
codePaths = ["app", "helper", "accomplice"]
subpathsToIgnore = [".git", "carthage", "pods", "build", ".build", "docs", "frameworks", "tests", "*/external", "*/SupportFiles", "*/iOS-Polynomial-Regression-master"]
localizablePaths = ["./Localization"]
transformer = "foundation"
supportedLanguageEnumPath = "."
typeName = "BartyCrouch"
translateMethodName = "translate"
separateWithEmptyLine = true

[update.normalize]
paths = ["app", "helper", "accomplice"]
subpathsToIgnore = [".git", "carthage", "pods", "build", ".build", "docs", "frameworks", "tests", "*/external", "*/SupportFiles", "*/iOS-Polynomial-Regression-master"]
sourceLocale = "de"
harmonizeWithSource = true
sortByKeys = true
separateWithEmptyLine = true

[lint]
paths = ["app", "helper", "accomplice"]
subpathsToIgnore = [".git", "carthage", "pods", "build", ".build", "docs", "frameworks", "tests", "*/external", "*/SupportFiles", "*/iOS-Polynomial-Regression-master"]
duplicateKeys = true
emptyValues = true
```

My CLT output looks like this
<img width="1546" alt="CleanShot 2022-08-15 at 17 57 43@2x" src="https://user-images.githubusercontent.com/40808343/184670855-f267fe73-0b55-45b2-afb5-cd32f4c4bcce.png">

I'm using an M1 MBA, and I'm working on the [`version-3` branch](https://github.com/noah-nuebling/mac-mouse-fix/tree/version-3) of the Mac Mouse Fix repo.

Not sure if relevant but the `normalize` task doesn't seem to output anything after the `...` so maybe there's something going wrong there?

_Originally posted by @noah-nuebling in https://github.com/FlineDev/BartyCrouch/issues/38#issuecomment-1215220638_
